name: CICD Test
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - macos-12
          - ubuntu-22.04
    runs-on: ${{ matrix.runner }}
    env:
      CGO_ENABLED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Setup Golang module caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-module-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-module-
      - name: Test
        run: go test ./...
